### ISSUE TITLE
Patch to compile on ODROID

### ISSUE THREAD

**Issue by neagix** [libretro/gambatte-libretro#10]
I have experienced some issues trying to compile current master on my ODROID device.

Please consider merging the following patch:

https://docs.google.com/file/d/0B_mVbKYzqk5-bTdHTnFmejlPSkk/edit?usp=sharing

It contains both bugfixes and improvements for ODROID platform (ARMv7). You might want to change the position of -fPIC

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#53
