### ISSUE TITLE
Internal Palette: GB - DMG seems a little bit off

### ISSUE THREAD

**Issue by RokkumanX** [libretro/gambatte-libretro#130]
Hello everyone!

When playing with the **Internal Palette: GB - DMG** core option I wondered how this came to be and what it's based on?

It looks like this:
![gb_dmg_gambatte](https://user-images.githubusercontent.com/50436544/57565790-e5a31d00-73c3-11e9-9e14-9eaacc02a49b.png)

While watching an episode of AVGN yesterday (Episode 42 - Virtual Boy) there was a brief moment of where a Game Boy screen was shown.
![gb_dmg_hardware](https://user-images.githubusercontent.com/50436544/57565806-564a3980-73c4-11e9-8e2e-a0c56abe807e.png)

By comparing these two and upon further examination it feels like the  **Internal Palette: GB - DMG** core option is a little bit off.

By using Paint and derivative the values of each color, lightest to darkest I was able to come up with this.
![gb_dmg_bgb](https://user-images.githubusercontent.com/50436544/57565838-fd2ed580-73c4-11e9-934d-90ed28f50bcb.png)

This pretty much resembles of how I remember the Game Boy games to look like.

These are the color values (used in bgb):
Color 1 - 120, 169, 59 (lightest)
Color 2 - 93, 150, 78
Color 3 - 70, 131, 89
Color 4 - 56, 110, 86 (darkest)

I don't think I have ever played a Game Boy that looks like the **Internal Palette: GB - DMG**
Granted, each individual Game Boy was unique however and it could just be my interpretation.

What do you guys think of this?

**Comment by RokkumanX** [comment]
I came up with a Default.pal real quick using the standalone Gambatte so I could test it out in RetroArch:

`[General]
Background0=7907643
Background1=6133326
Background2=4621145
Background3=3698262
Sprite%2010=7907643
Sprite%2011=6133326
Sprite%2012=4621145
Sprite%2013=3698262
Sprite%2020=7907643
Sprite%2021=6133326
Sprite%2022=4621145
Sprite%2023=3698262
slectedScheme=DEFAULT`

**Internal Palette: GB - DMG**
![dmg_2](https://user-images.githubusercontent.com/50436544/57568046-2ad64780-73e2-11e9-988c-1573342e06cb.png)

**Derivation from Game Boy screen image** 
![dmg_1](https://user-images.githubusercontent.com/50436544/57568066-5b1de600-73e2-11e9-8ca5-c3e7f2c9759b.png)

The screens are quite blurry due to the fact that I am using the Response time shader but otherwise it looks good.

I have been on a quest for the perfect Game Boy palette for over 4 years now and I can't say either one is the definitive 100% and I have tried out a dozen ones through the course of time.

But the derivation one feels most right to me compared to Internal Palette: GB - DMG

The debate is open so feel free to chime in with your thoughts and opinions.

**Comment by RokkumanX** [comment]
Since I own two Game Boys myself this was the best I could come up with.

![dmg_hardware1](https://user-images.githubusercontent.com/50436544/57569568-105a9900-73f7-11e9-8cd7-01f3f6ee8891.JPG)

![dmg_hardware2](https://user-images.githubusercontent.com/50436544/57569573-19e40100-73f7-11e9-85d6-6479cea3fb35.JPG)

Clearly these images doesn't do the quest for the perfect palette any justice and the Game Boys I have haven't aged very well.

The AVGN screen capture of a Game Boy screen is the best I have, no matter which angle or view every shot I took looked as bad as these two captures I posted.

And to add more frustration to this the brightness adjustment sliders on my two Game Boys seemed to work poorly.
Either the screen got to bright or to dark and I made sure that the batteries were new and full.

**Comment by RokkumanX** [comment]
By enhancing the resolution from the Yellow Game Boy image and examine it further I was enable to make a rough and quick translation into bgb.

![dmg_rough](https://user-images.githubusercontent.com/50436544/57570928-abf40580-7407-11e9-85e7-64426bc152ab.png)

I was quite satisfied with the result but the Egg doesn't quite look the same, the dots in the original Yellow Game Boy image looks darker than the final result in the emulator but again this is just a rough approximation and interpretation.

At this point I don't know what do base a "true" palette on frankly, it could be literally thousands of combinations.

In the end it's what the end user remembers it to be but making a palette based on the AVGN Game Boy screen seems to be "the" choice at the moment, it's not to bright and it's not to dark either.

**Comment by RokkumanX** [comment]
The quest for perfection continues!

I scoured the net and stumbled upon something similar to the AVGN Game Boy screen.

![dmg_hardware_screen](https://user-images.githubusercontent.com/50436544/57574621-b250a480-743c-11e9-9c01-cc91bebe90e1.jpg)

It's not that bad actually and the first T in Tetris contains everything you need for a complete palette.

![palette](https://user-images.githubusercontent.com/50436544/57574639-f93e9a00-743c-11e9-97d6-b49f4870fb1e.jpg)

This means we could use this to make a quite accurate palette with good balance of brightness and darkness.

My own Game Boy screens were quite dark and I wasn't even close getting the same quality or brightness like these.

One step closer to achieve victory!

**Comment by hizzlekizzle** [comment]
That looks too lime-green and blue to me.
![image](https://user-images.githubusercontent.com/2805586/57576118-71499780-741e-11e9-8c38-66c8ac923a5c.png)
This looks more like I remember ^^

It's surprisingly hard to find good photos for game boys online. Most of the ones I clicked on ended up being RetroArch with harlequin's gameboy shader...

**Comment by RokkumanX** [comment]
It is indeed hard to find good photos of a "healthy" Game Boy screen and I can't say there is nothing wrong with the one you posted, maybe just a little to bright.

By translating the palette from the Tetris image I created a quick mockup

![dmg_moccup](https://user-images.githubusercontent.com/50436544/57578332-72181300-748a-11e9-816a-fb809f7f2ed0.png)

This is probably as good as it gonna get, and while it's not perfect it's the closest I have come replicating the Game Boy.

I need to test it with other games just to make sure but the boot animation looks really good too though.

**Comment by RokkumanX** [comment]
After much consideration I have now reached the conclusion to close the issue.

Game Boy palettes/screens is what you remember it to be, I'm not the one saying which one is more right than the other.

There are literally thousands of different combinations and types of Game Boy screens which each have different and unique abilities.

If you find a palette that suits you it's better to just make one in standalone Gambatte and create a Default.pal for use in RetroArch.

Thank you so much for everything!

**Comment by hizzlekizzle** [comment]
I think that's probably an accurate statement. As I was looking over images and remembering, etc., I was considering how much the image changed based on the contrast slider. I always kept mine very low because I was a battery miser. I can imagine people who kept theirs at a higher contrast level probably have a very different image in mind.

**Comment by RokkumanX** [comment]
Exactly, there isn't a definite Game Boy palette, I realize that now.
It's up to each and everyone to decide what to use and a Custom palette is the best way to go.
