### ISSUE TITLE
Track map flickers on F-Zero Maximum Velocity

### ISSUE THREAD

**Issue by detectorcaleta1** [libretro/gambatte-libretro#145]
Hello, 

Map flickers on any track, (map is located on the bottom left on the screen), on both GL and Vulkan API, please fix it. I cannot even take a picture of it because when it flickers, the screenshot doesn't get captured.

Thank you very much.

**Comment by negativeExponent** [comment]
this is an invalid report since F-Zero Maximum Velocity is a Game Boy Advanced game.
