### ISSUE TITLE
No Sound at all

### ISSUE THREAD

**Issue by TradeDraft** [libretro/gambatte-libretro#170]
I am using Windows 10 64 Bit Version and Latest Gambatte Core from here:

https://git.libretro.com/explore

Then when you load up there is no Sound at all.

Same on Different Audio Drivers

**Comment by bslenul** [comment]
Yup no sound on Windows 10 for me as well, started with a0a0f84238ed84b3540f86d2b6f2943bc4aa8961

"Volume %" core options are at "100". No issue on my Linux Mint VM however.

**Comment by pa-august** [comment]
No sound on Wii U either.

**Comment by SeraphisCain** [comment]
No sound here on Pi 4 as well.

**Comment by cmitu** [comment]
Bisected to a0a0f84238ed84b3540f86d2b6f2943bc4aa8961 (from #166).

**Comment by marcdziadek** [comment]
I'm running lr-gambatte on a Pi Zero (with GPi Case). 
This morning I updated lr-gambatte (install from source based on commit '0af99f87eaec7b46f64b260028fa328c0c15c72d') and sound is back :). 

Now lr-gambatte has sound AND working Net Link. X-Mas can come.... :D

THX
