### ISSUE TITLE
Retropie 4.7.13 on a Pi4 4GB - After update possibly audio glitch ?

### ISSUE THREAD

**Issue by DjDiabolik** [libretro/gambatte-libretro#186]
Recently the lr-gamebatte has obtain some update ?

Yesterday i have update my Retropie setup on my Pi4 4GB. I have complete all upgrade and i have reboot my Pi4 (because some OS components as been updated).

Now, during play a games i can listen some trouble on audio. It's like some parts it's cutted out or glitch or some frames as been skipped...... it's somethings changed ?

**Comment by LibretroAdmin** [comment]
Not sure what to make of this, going to close it for now

**Comment by DjDiabolik** [comment]
OMG what a old report. I have also discuss regarding this issue on a thread open in retropie.co.uk board.....
