### ISSUE TITLE
Core options are not shown with the latest core version

### ISSUE THREAD

**Issue by ToniBC** [libretro/gambatte-libretro#199]
With the latest additions, something happened with the core options that are no longer displayed. There is only one option, the rest disappeared and nothing can be configured.

All this tested with the version of Windows 10 x64, with the latest nightly to date and the core in its version 37901de.

Thanks.

**Comment by Ryunam** [comment]
I just compiled the latest core for Windows 10 x64 (304d64d) and core options are now showing up properly. Just give the buildbot some time to catch up and it should be fixed.

**Comment by ToniBC** [comment]
Thanks, everything works again.
