### ISSUE TITLE
I have 45 palettes that I made back when bittboy came out. Can this be added into gambatte retroarch core?

### ISSUE THREAD

**Issue by PixelShift-gb** [libretro/gambatte-libretro#219]
Here is 45 palettes that I made back when the bittboy system initially released and gambatte was ported to that system.

I would greatly appreciate it if you could add these to the build, these were not done in haste, they were made with a purpose and to not have any filler. If you do add them please add them under the name PixelShift. My discord is PixelShift#2272.

I specially enjoy the hardware inspired palettes, as i used photoshop and recreated a lot of modded front light gameboys and actually tested them to make sure it mimicked the real thing.

Sorry if this is not the place to ask, I've tried emailing the gambatte owner but the email I could find at the time didnt send through.

**Artistic** ![p2](https://user-images.githubusercontent.com/2074620/148480818-74f3cb94-7515-437c-aaad-e1b5e05b8465.png)
**Hardware Inspired** ![p](https://user-images.githubusercontent.com/2074620/148480819-ada72433-58a0-44d8-a04f-be29f0bd6937.png)
**Download**
[PixelShift's Palettes.zip](https://github.com/libretro/gambatte-libretro/files/7825887/PixelShift.s.Palettes.zip)

**Comment by jimgraygit** [comment]
Whoa, these are awesome!

**Comment by jdgleaver** [comment]
@PixelShift-gb Hi! I only just noticed your issue/request yesterday, Your palettes are excellent, so I've added them to the core in this PR: https://github.com/libretro/gambatte-libretro/pull/225
