### ISSUE TITLE
custom palette "default.pal" doesn't get used anymore

### ISSUE THREAD

**Issue by pantra64** [libretro/gambatte-libretro#22]
in earlier gambatte-libretro builds (some time around RetroArch 0.9.7 I think) if there existed a custom palette <system>/palettes/default.pal it would get loaded and used. Not so anymore, maybe since the gbc bios palettes were built into the core. Only .pal-files that are named after their game are still used, for example "SUPERMARIOLAND3.pal".

**Comment by netux79** [comment]
This is no longer an issue... it have been working fine for more than a year :). Please close

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#54
