### ISSUE TITLE
Porn Ass Sexy Sex

### ISSUE THREAD

**Issue by PatrickStar2007** [libretro/gambatte-libretro#227]
http://porn.com
http://sex.com
Asshole fucked fuck fuckers bitches bitch ass nigger nigga faggot
![1643104929_Young-lady-seen-watching-p0rn-in-a-bus-filled-with](https://user-images.githubusercontent.com/101215826/162582365-f96ccd8e-60f5-47d8-9535-3ae3e484f02a.jpg)
![1000_F_123908235_19GnmAYaEDpVKoToPBrI32ryIfFq9CP1](https://user-images.githubusercontent.com/101215826/162582368-9b7b5246-2588-442b-8fde-3381280822bd.jpg)
![istockphoto-186825263-612x612](https://user-images.githubusercontent.com/101215826/162582371-478f3ffa-def4-4353-a780-d7ade0e8bfdf.jpg)
![blood](https://user-images.githubusercontent.com/101215826/162582375-c4b4e4fc-64eb-4ebc-9436-8a2dac89c1b1.jpg)
![PWOct19_blood-spatter_HERO](https://user-images.githubusercontent.com/101215826/162582378-6f1bbf0f-7185-4d8e-94a2-04bcb3b7c277.jpg)
![2adb092b-1726-4e56-a0dd-30056756ddae](https://user-images.githubusercontent.com/101215826/162582386-ee2dc9dc-ff0b-4312-b16d-a0972b38aa3f.jpg)

**Comment by twinaphex** [comment]
Reported to Github for sexually explicit content. Will remove post after the report has been processed by Github.
