### ISSUE TITLE
GB - TWB64 Pack 2/3 are not working

### ISSUE THREAD

**Issue by GlaZedBelmont** [libretro/gambatte-libretro#256]
After testing on JelOS and Retroarch for PC, Gambatte's TWB64 - Pack 3 palettes simply don't work and automatically revert to GBC - Grayscale , switching palettes with L/R also is extremely wonky and just skips over to default palettes or pixelshift/SGB.

Tested on latest commit ([327137e](https://github.com/libretro/gambatte-libretro/commit/327137ec04d514b6c06c30c8b1d0b5da4267af6c)) on both platforms
![retroarch_GcplBu2zzp](https://github.com/libretro/gambatte-libretro/assets/48196637/c8f3f372-ff34-485c-925e-eebdbc22ff34)

EDIT: The linked PR does NOT fix those palettes, just to be clear

**Comment by Starlightbotanist** [comment]
I'm able to reproduce this issue on Android as well.
