### ISSUE TITLE
Build issue for Android ndk

### ISSUE THREAD

**Issue by meancoot** [libretro/gambatte-libretro#3]
There is an issue with building this for Android. With INCDIRS using the -I${PATH} form the build system will eventually pick up gambatte's memory.h in place of Android's file with the same name.

The simple fix is to replace all entries in INCDIRS with the -iqoute ${PATH} form, then change <gambatte.h> to "gambatte.h" in libretro.cpp.

The environment I use to build is 'platform=unix CC=arm-linux-androideabi-gcc CXX=arm-linux-androideabi-g++'

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#35

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#36
