### ISSUE TITLE
Crash with RetroArch Windows 10/7 Build

### ISSUE THREAD

**Issue by Awakened0** [libretro/gambatte-libretro#34]
This core is crashing for me as of the latest test build. Here is my log:

F:\Blue\Emulation\Emulators\RetroArch>retroarch.exe "....\Roms\Nintendo Game Bo
y\Wario Land - Super Mario Land 3 (World).zip"  -c Config\GBA.cfg --appendconfig
 Config\GB.cfg --verbose
rarch_main_init: === Build =======================================
Compiler: MinGW (4.9.1) 64-bit
Built: Oct  7 2014
rarch_main_init: Version: 1.0.0.2-2014-10-07
rarch_main_init: Git: 7270f89
rarch_main_init: =================================================
RetroArch: rarch_get_cpu_features: [CPUID]: Vendor: GenuineIntel
RetroArch: rarch_get_cpu_features: [CPUID]: MMX:    1
RetroArch: rarch_get_cpu_features: [CPUID]: MMXEXT: 1
RetroArch: rarch_get_cpu_features: [CPUID]: SSE:    1
RetroArch: rarch_get_cpu_features: [CPUID]: SSE2:   1
RetroArch: rarch_get_cpu_features: [CPUID]: SSE3:   1
RetroArch: rarch_get_cpu_features: [CPUID]: SSSE3:  1
RetroArch: rarch_get_cpu_features: [CPUID]: SSE4:   1
RetroArch: rarch_get_cpu_features: [CPUID]: SSE4.2: 1
RetroArch: rarch_get_cpu_features: [CPUID]: AES:    1
RetroArch: rarch_get_cpu_features: [CPUID]: AVX:    1
RetroArch: rarch_get_cpu_features: [CPUID]: AVX2:   0
RetroArch: parse_config_file: Loading config from: Config\GBA.cfg.
RetroArch: config_load_file: Appending config "Config\GB.cfg"
config_load_file: === Config ===
RetroArch: config_file_dump_all: video_shader = "./Shaders/gb-pocket-shader.cgp"

RetroArch: config_file_dump_all: rgui_browser_directory = "../../Roms/Nintendo G
ame Boy/"
RetroArch: config_file_dump_all: savefile_directory = "./Save/Nintendo Game Boy
Color/"
RetroArch: config_file_dump_all: savestate_directory = "./State/Nintendo Game Bo
y Color/"
RetroArch: config_file_dump_all: system_directory = "./System/Nintendo Game Boy
Color/"
RetroArch: config_file_dump_all: libretro_path = "./Cores/gambatte_libretro.dll"

RetroArch: config_file_dump_all: audio_volume = "5.0"
RetroArch: config_file_dump_all: video_driver = "gl"
RetroArch: config_file_dump_all: audio_driver = "dsound"
RetroArch: config_file_dump_all: video_fullscreen = "true"
RetroArch: config_file_dump_all: config_save_on_exit = "false"
RetroArch: config_file_dump_all: input_autodetect_enable = "false"
RetroArch: config_file_dump_all: input_joypad_driver = "winxinput"
RetroArch: config_file_dump_all: input_player1_joypad_index = "0"
RetroArch: config_file_dump_all: input_player1_a_axis = "nul"
RetroArch: config_file_dump_all: input_player1_a_btn = "0"
RetroArch: config_file_dump_all: input_player1_a = "z"
RetroArch: config_file_dump_all: input_player1_b_axis = "nul"
RetroArch: config_file_dump_all: input_player1_b_btn = "2"
RetroArch: config_file_dump_all: input_player1_b = "x"
RetroArch: config_file_dump_all: input_player1_select_axis = "nul"
RetroArch: config_file_dump_all: input_player1_select_btn = "7"
RetroArch: config_file_dump_all: input_player1_select = "c"
RetroArch: config_file_dump_all: input_player1_start_axis = "nul"
RetroArch: config_file_dump_all: input_player1_start_btn = "6"
RetroArch: config_file_dump_all: input_player1_start = "enter"
RetroArch: config_file_dump_all: input_player1_l_axis = "nul"
RetroArch: config_file_dump_all: input_player1_l_btn = "4"
RetroArch: config_file_dump_all: input_player1_l = "a"
RetroArch: config_file_dump_all: input_player1_r_axis = "nul"
RetroArch: config_file_dump_all: input_player1_r_btn = "5"
RetroArch: config_file_dump_all: input_player1_r = "s"
RetroArch: config_file_dump_all: input_player1_left_axis = "nul"
RetroArch: config_file_dump_all: input_player1_left_btn = "h0left"
RetroArch: config_file_dump_all: input_player1_left = "left"
RetroArch: config_file_dump_all: input_player1_right_axis = "nul"
RetroArch: config_file_dump_all: input_player1_right_btn = "h0right"
RetroArch: config_file_dump_all: input_player1_right = "right"
RetroArch: config_file_dump_all: input_player1_up_axis = "nul"
RetroArch: config_file_dump_all: input_player1_up_btn = "h0up"
RetroArch: config_file_dump_all: input_player1_up = "up"
RetroArch: config_file_dump_all: input_player1_down_axis = "nul"
RetroArch: config_file_dump_all: input_player1_down_btn = "h0down"
RetroArch: config_file_dump_all: input_player1_down = "down"
RetroArch: config_file_dump_all: input_player1_analog_dpad_mode = "1"
RetroArch: config_file_dump_all: input_player1_l_x_plus = "nul"
RetroArch: config_file_dump_all: input_player1_l_x_plus_btn = "nul"
RetroArch: config_file_dump_all: input_player1_l_x_plus_axis = "+0"
RetroArch: config_file_dump_all: input_player1_l_x_minus = "nul"
RetroArch: config_file_dump_all: input_player1_l_x_minus_btn = "nul"
RetroArch: config_file_dump_all: input_player1_l_x_minus_axis = "-0"
RetroArch: config_file_dump_all: input_player1_l_y_plus = "nul"
RetroArch: config_file_dump_all: input_player1_l_y_plus_btn = "nul"
RetroArch: config_file_dump_all: input_player1_l_y_plus_axis = "-1"
RetroArch: config_file_dump_all: input_player1_l_y_minus = "nul"
RetroArch: config_file_dump_all: input_player1_l_y_minus_btn = "nul"
RetroArch: config_file_dump_all: input_player1_l_y_minus_axis = "+1"
RetroArch: config_file_dump_all: input_hold_fast_forward_axis = "+5"
RetroArch: config_file_dump_all: input_hold_fast_forward_btn = "nul"
RetroArch: config_file_dump_all: input_hold_fast_forward = "tilde"
RetroArch: config_file_dump_all: input_shader_prev_btn = "9"
RetroArch: config_file_dump_all: input_exit_emulator_btn = "10"
RetroArch: config_file_dump_all: input_menu_toggle_axis = "nul"
RetroArch: config_file_dump_all: input_menu_toggle_btn = "8"
RetroArch: config_file_dump_all: input_menu_toggle = "tab"
RetroArch: config_file_dump_all: input_save_state_axis = "nul"
RetroArch: config_file_dump_all: input_save_state_btn = "nul"
RetroArch: config_file_dump_all: input_save_state = "f5"
RetroArch: config_file_dump_all: input_load_state_axis = "nul"
RetroArch: config_file_dump_all: input_load_state_btn = "nul"
RetroArch: config_file_dump_all: input_load_state = "f9"
RetroArch: config_file_dump_all: input_audio_mute_axis = "nul"
RetroArch: config_file_dump_all: input_audio_mute_btn = "nul"
RetroArch: config_file_dump_all: input_audio_mute = "f2"
RetroArch: config_file_dump_all: input_reset_axis = "nul"
RetroArch: config_file_dump_all: input_reset_btn = "nul"
RetroArch: config_file_dump_all: input_reset = "f10"
RetroArch: config_file_dump_all: video_smooth = "false"
RetroArch: config_file_dump_all: video_scale_integer = "false"
RetroArch: config_file_dump_all: video_windowed_fullscreen = "true"
RetroArch: config_file_dump_all: video_disable_composition = "false"
RetroArch: config_file_dump_all: video_vsync = "true"
RetroArch: config_file_dump_all: video_hard_sync = "true"
RetroArch: config_file_dump_all: video_hard_sync_frames = "0"
RetroArch: config_file_dump_all: video_swap_interval = "2"
RetroArch: config_file_dump_all: video_refresh_rate = "60.000000"
RetroArch: config_file_dump_all: video_shader_enable = "true"
RetroArch: config_file_dump_all: rgui_browser_directory = "../../Roms/Nintendo G
ame Boy Advance/"
RetroArch: config_file_dump_all: savefile_directory = "./Save/Nintendo Game Boy
Advance/"
RetroArch: config_file_dump_all: savestate_directory = "./State/Nintendo Game Bo
y Advance/"
RetroArch: config_file_dump_all: screenshot_directory = "./Screenshot/"
RetroArch: config_file_dump_all: video_shader_dir = "./Shaders/"
RetroArch: config_file_dump_all: system_directory = "./System/"
RetroArch: config_file_dump_all: video_shader = "./Shaders/lcd-shader.cgp"
RetroArch: config_file_dump_all: libretro_path = "./Cores/vbam_libretro.dll"
RetroArch: config_file_dump_all: video_scale = "6.0"
RetroArch: config_file_dump_all: pause_nonactive = "true"
RetroArch: config_file_dump_all: autosave_interval = "60"
RetroArch: config_file_dump_all: audio_volume = "3.0"
RetroArch: config_file_dump_all: rgui_show_start_screen = "false"
config_load_file: === Config end ===
RetroArch: load_symbols: Loading dynamic libretro from: "F:\Blue\Emulation\Emula
tors\RetroArch\Cores\gambatte_libretro.dll"
RetroArch: rarch_environment_cb: Environ SET_VARIABLES.
RetroArch: parse_variable: Core option:
RetroArch: parse_variable:      Description: GBA mode
RetroArch: parse_variable:      Key: gb_gbamode
RetroArch: parse_variable:      Current value: disabled
RetroArch: parse_variable:      Possible values:
RetroArch: parse_variable:              disabled
RetroArch: parse_variable:              enabled
RetroArch: parse_variable: Core option:
RetroArch: parse_variable:      Description: GB Colorization
RetroArch: parse_variable:      Key: gb_colorization
RetroArch: parse_variable:      Current value: disabled
RetroArch: parse_variable:      Possible values:
RetroArch: parse_variable:              disabled
RetroArch: parse_variable:              enabled
RetroArch: parse_variable:              custom
RetroArch: parse_variable: Core option:
RetroArch: parse_variable:      Description: Color correction
RetroArch: parse_variable:      Key: gbc_color_correction
RetroArch: parse_variable:      Current value: enabled
RetroArch: parse_variable:      Possible values:
RetroArch: parse_variable:              enabled
RetroArch: parse_variable:              disabled
RetroArch: verify_api_version: Version of libretro API: 1
RetroArch: verify_api_version: Compiled against API: 1
RetroArch: rarch_environment_cb: Environ GET_LOG_INTERFACE.
RetroArch: rarch_environment_cb: Environ PERFORMANCE_LEVEL: 4.

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#57
