### ISSUE TITLE
Support for 128kb sav

### ISSUE THREAD

**Issue by jkjwong** [libretro/gambatte-libretro#41]
Would it be possible to add support for 128kb .sav files / SRAM dump? This will help with compatibility with other emulators and also support roms like LSDJ (little sound dj).

**Comment by MarioMaster100** [comment]
Yes please! Instead of creating a 128kb .srm it's making a 131.1 kb .srm

**Comment by Alcaro** [comment]
You're using [different kilobytes](http://blog.forret.com/2005/02/04/binary-confusion-kilobytes-and-kibibytes/), 128 and 131.1 is the same.

If it's creating ~130KB files, then I'm pretty sure the problem was solved at some point during the last year.

**Comment by MarioMaster100** [comment]
Well I copy the .srm to my phone and try to use it on gambatte under retroarch and it doesn't load the proper file and the same thing happens on my 2DS.

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#58
