### ISSUE TITLE
Rumble support

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/gambatte-libretro#46]
There are 23 games with rumble support, should be interesting to add this feature to Gambatte. Some games also support rumble even without it in the cartridge, like Tarzan.

MBC5 mapper is implemented in VBA-M, and in the VBA GX port it's fully implemented.

https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/gb/gbMemory.cpp#L533

https://github.com/dborth/vba-wii/blob/master/source/vba/gb/gbMemory.cpp#L534

Someone in the forum also requested it: http://libretro.com/forums/showthread.php?t=991

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#43

**Comment by ToniBC** [comment]
This version is not yet available to test if the vibration works, at least in Windows x64 versions. The last version compiled by the buildbot is from November 11th.

I don't know if it's queued to compile with the new buildbot or skipped the process with the switch to the new system.

It would be nice to force the compilation if so.
