### ISSUE TITLE
[Android] Gambette- Is colorization broken?

### ISSUE THREAD

**Issue by SuperL2** [libretro/gambatte-libretro#48]
I have spent the last couple of days, in vain, trying to get a custom palette working in Gambette for Retroarch android. Specifically, a pea-green GB palette so I don't have to rely on the battery-taxing shader.

Apparently, users of Retroarch on other systems have gotten colorization to work fine. But on Android, I'm fairly certain it's broken. The Special palettes fail to load anything, and choosing custom does not load the proper .pal file, and the palette defaults to whatever the last internal palette was.

My palette files are located in /data/data/com.retroarch/system/palettes, and read/write/execute privileges have been granted to all files and folders. But still nothing. I must thus add this issue.

**Comment by SuperL2** [comment]
I got the issue resolved. Basically, retroarch treats the palette files like BIOS files, and they have to be in the same directory as BIOS files to work. I didn't grasp that until today.

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#60
