### ISSUE TITLE
Compilation with gcc 6.1.1 fails with narrowing conversion error

### ISSUE THREAD

**Issue by neilmunday** [libretro/gambatte-libretro#52]
Since commit f08f01cf0ed6f249345b093cb05af6c3e2114c59 I am unable to compile gambatte-libretro using GCC 6.1.1 as it fails with the following error:

src/../libretro/libretro.cpp:521:4: error: narrowing conversion of '-8192' from 'int' to 'size_t {aka unsigned int}' inside { } [-Wnarrowing]
    };

Commit 755883d2e2b4488cef3a58b422e5b80aa9eb29f1 (and before) work fine.

**Comment by neilmunday** [comment]
Thanks for the quick response. Cheers, Neil.

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#61
