### ISSUE TITLE
Graphic glitches in Street Fighter 2

### ISSUE THREAD

**Issue by arakerlu** [libretro/gambatte-libretro#54]
The graphics in Street Fighter 2 are glitching, as can be seen in this [video](https://cloud.githubusercontent.com/assets/19595911/15976234/20fd0e26-2f5a-11e6-8021-72b15ddaaacd.gif). I'm using the Windows version and the problem is easily reproduced in the latest version.

[Video](https://cloud.githubusercontent.com/assets/19595911/15976234/20fd0e26-2f5a-11e6-8021-72b15ddaaacd.gif)

**Comment by arakerlu** [comment]
I found out that this problem doesn't reproduce in Gambatte so I decided to find out when exactly was it fixed in Gambatte. After some manual binary search, I discovered the couple of commits back from Aug-Sep 2012 that fixed the problem here. 

I have backported the commits from gambatte in my branch of gambatte-libretro, tested them for some time and it seems to work as expected - meaning that the Street Fighter 2 glitch doesn't reproduce anymore and it hasn't brought any other undesired effects. 

My commit backporting the commits from gambatte is here:
https://github.com/arakerlu/gambatte-libretro/commit/106324144d07ebe73d722125e59ddd632b3b6696

**Comment by hizzlekizzle** [comment]
That looks good. Would you want to submit a pull request?

**Comment by arakerlu** [comment]
Thanks. Sure I will.

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#62
