### ISSUE TITLE
Rom loading broken on PSP Retroarch 1.3.6

### ISSUE THREAD

**Issue by larrykoubiak** [libretro/gambatte-libretro#57]
Core loading seems to go fine, but when loading a rom the screen goes to black then either crashes back to menu or just freezes.

Retroarch 1.3.6 on PSP 3010.

**Comment by twinaphex** [comment]
With which cores?

**Comment by larrykoubiak** [comment]
Gambatte 0.5.0

**Comment by twinaphex** [comment]
I'll check out the PSP version today or tomorrow and see what is up.

**Comment by larrykoubiak** [comment]
ok thx, in the meantime i reverted to 1.3.0, works fine there

**Comment by MoochMcGee** [comment]
I'm having the same issue.

**Comment by Keytharsis** [comment]
Yup same issue on a fresh install PSP 2004, both gambatte and TempGBA go to black screen and crash.

**Comment by MoochMcGee** [comment]
Yeah, it turns off the PSP too.

**Comment by Keytharsis** [comment]
1.2.2 => Gambattte is OK, TempGBA is OK
1.3.0 => Gambatte is OK TempGBA is not

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#44
