### ISSUE TITLE
color correction option not effective with custom palettes

### ISSUE THREAD

**Issue by eadmaster** [libretro/gambatte-libretro#63]
The color correction core option is not honored if the colorization mode is set to "custom".

**Comment by Alcaro** [comment]
(Untested) May be fixable by moving libretro.cpp:392-396 to the end of check_variables

**Comment by eadmaster** [comment]
I've done some extra testing with some palettes generated from vanilla Gambatte, and it seems the current code is correct while [my old palettes collection] is not (http://eadmaster.altervista.org/pub/prj/goomba_txt2gambatte_pal.zip).

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#63
