### ISSUE TITLE
[Wii] Gamecube controller repeatedly detected

### ISSUE THREAD

**Issue by Joechinchains** [libretro/gambatte-libretro#68]
When using the Gamebatte Retroarch core with a Gamecube controller in the first slot, the automatic detection and remapping of the controller will happen over and over, displaying the message "Gamecube controller configured in Port #00" at the bottom of the screen. The display can be triggered consistently by certain acts in a game, such as entering a door or sucking up an enemy in Kirby's Dream Land or moving between menus in Mario Golf, but generally speaking it appears near-constantly in the majority of games. This behavior does not happen with the Wiimote or any other controller, nor any other core on Retroarch Wii that I've seen.

Although you can disable automatic remapping, due to the way Retroarch on the console works there is no way to manually remap the controls without first disabling the current set and totally locking yourself out of any control until you delete the retroarch.cfg file. There is also no option to disable the message that I can see.

Retro Version: 1.3.4
Emu Version: Gambatte v0.5.0

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#48

**Comment by filevans** [comment]
@Joechinchains did you ever manage to remap the gamecube controller? I'm trying to remap the GameCube controller particularly for cps1 and 2 as they are a bad layout, but when I try it won't register key presses, I'm pretty sure the cfg files have to be edited on pc but can't do it and there seems to be no help online

Thanks a lot
