### ISSUE TITLE
Control Mapping Retropad Issue

### ISSUE THREAD

**Issue by Gurk232** [libretro/gambatte-libretro#69]
Hi there, having an issue with Gambatte where instead of the core having its own control config, it uses retropad directly. So instead of mapping just the core it remaps retropad for all other cores, the controls are also not changed in input to reflect changes made and the only way to reset control mappings to normal is via Gambatte.

This is contrasted to something like Snes9x which has a "SNES pad" setting and changes made in "controls" only affect the Snes9x core.

Using RetroArch 1.4.1 on Android, core is Gambatte v0.5.0-netlink.

Thank you much.

**Comment by hizzlekizzle** [comment]
To remap controls for a core, don't use the input mapping in settings > input, use the ones in quick menu > controls. Those will only affect the individual core and won't bleed over to other cores.

**Comment by Gurk232** [comment]
That's what I mean, remapping through quick menu> controls bleeds over into other cores with gambatte

**Comment by fr500** [comment]
that's not possible

**Comment by Gurk232** [comment]
I'll do a little more testing with it, hold on

**Comment by Gurk232** [comment]
This seems to be only be affecting mupen64, let me check and see if that's the case for any other cores.

So for example if I swap the button positions of a and b in gambatte, and have it load up a remap, then switch over to mupen64, mupen64 will also have swapped buttons of a and b in the same position despite the remap file being different.

**Comment by Gurk232** [comment]
Okay, so this is exclusively a mupen64 problem, loading in any another core with a remap and then loading into mupen64 seems to be the issue.

I can close this and move it over to mupen64 if you want.

**Comment by Gurk232** [comment]
It seems Gambatte at least is working as intended

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#64
