### ISSUE TITLE
Some targets are failing to build now

### ISSUE THREAD

**Issue by fr500** [libretro/gambatte-libretro#77]
<AlcaRobot> retroarch: [status: fail] [recipes/nintendo/wiiu] LOG: http://p.0bl.net/2255
<AlcaRobot> retroarch: [status: fail] [recipes/nintendo/wii] LOG: http://p.0bl.net/2256
<AlcaRobot> retroarch: [status: fail] [recipes/nintendo/gamecube] LOG: http://p.0bl.net/2257

**Comment by aliaspider** [comment]
fixed in fafc291217c4fdb5a25c3543694fc3b3238e3ccb

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#65
