### ISSUE TITLE
Save file deletion when using RetroArch's built-in reset function with Gambatte libretro

### ISSUE THREAD

**Issue by Monroe88** [libretro/gambatte-libretro#9]
On RetroArch 0.9.8, on Windows 7 x64, with the latest Gambatte libretro available through the built-in updater, using the reset function through RetroArch causes the game's battery save to be wiped. I came across this when playing The Legend of Zelda Oracle of Seasons and found that it happens in every game with a save function that I've tried

**Comment by sergiobenrocha2** [comment]
This issue was moved to libretro/libretro-meta#52
