### ISSUE TITLE
README to README.md

### ISSUE THREAD

**Issue by vishhvaan** [libretro/gambatte-libretro#90]
when RetroPie is cloning this repo, it looks for README and not README.md. This causes the RetroPie installer to crash. 

![readme](https://user-images.githubusercontent.com/34782145/34315531-879c824c-e746-11e7-884c-9cef71684d3c.png)

**Comment by bnied** [comment]
+1

**Comment by bnied** [comment]
Looks like this is fixed by updating to the latest version of the Retropie-Setup script.
