### ISSUE TITLE
Broken portability

### ISSUE THREAD

**Issue by hi-ban** [libretro/gambatte-libretro#95]
When trying to build core without` __LIBRETRO__` flag, we get the following errors:

src/gambatte-memory.h:61:2: error: 'class gambatte::Cartridge' has no member named 'loadSavedata'
void loadSavedata() { cart_.loadSavedata(); }
src/gambatte-memory.h:62:2: error: 'class gambatte::Cartridge' has no member named 'saveSavedata'
void loadSavedata() { cart_.loadSavedata(); }

Seems that at some point portability was broken. No idea how many more functions are missing, as the build process just stops there.

**Comment by fr500** [comment]
Why would you build our fork without __LIBRETRO__?

**Comment by hi-ban** [comment]
There are other projects (non-libretro) which use the gambatte core, and i'd like to use an updated gambatte core instead of an old one from 2009.

**Comment by meepingsnesroms** [comment]
What are you trying to do with it, could you compile it with libretro and just make a small libretro wrapper?

Libretro just remaps basic functions in a standardized way so if staticly linked the libretro bindings would just be optimized out.
