### ISSUE TITLE
MBC7 ROM support - Game Boy Color

### ISSUE THREAD

**Issue by edwardsd97** [libretro/gambatte-libretro#96]
Roms like Kirby Tilt n Tumble do not work as they use a data format that gambatte does not support.

Apparently Visual Boy Advance has some code that might be portable for this

https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/gb/gbMemory.h#L50
https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/gb/gbMemory.cpp#L664

I took a look at doing the port myself but the differences in operations between VBA and gambatte are a bit mysterious to me. Someone with more experience with these codebases might have a better time with it.

**Comment by sergiobenrocha2** [comment]
See #33

**Comment by hizzlekizzle** [comment]
Closed for duplicate issue.
