### ISSUE TITLE
Vita: Sporadically freezes while loading a Save State

### ISSUE THREAD

**Issue by xadox-1st** [libretro/gambatte-libretro#97]
Having trouble loading save states in Gambatte on Vita Enso 3.65 with several GB games.
Around 40-70% loading tryies are loading fine, the rest are freezing.
OSD is freezing at _"0% loading state"_.

Can not enter RetroArch menu anymore while it freezed. Have to close the program with the PS button and restart RetroArch.

The following roms have I tried so far:
- Amazing Spider-Man, The (USA, Europe)
- Mega Man - Dr. Wily's Revenge (USA)
- SolarStriker (World)
- Super Mario Land (World) (Rev A)

Problem occurs with v1.7.1 and nightly from 2018-03-28.
The maching bios files are used. Tryied with fresh and clean _retroarch.cfg_, also.

**Comment by gregorehk** [comment]
Hi I am having the same issue and have done some additional testing.

Vita Enso 3.65, Vita 2000, tested RetroArch 1.7.3 and 1.7.0

Core behavior;
Gambatte - Freezes at 55% when loading state, app has to be killed to fix
GearBoy - Displays that it has loaded 100% but does nothing
TGB Dual - Works fine

Games tested;
GBC - Aladdin
GBC - Zelda OOA
GB - Super Mario Land
GB - Adams Family
